
#ifndef RESOURCE_H
#define RESOURCE_H

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_DICTIONARY                   110
#define IDD_DIALOG_SKK_DIC_ADD_URL				111
#define IDD_DIALOG_BEHAVIOR1                    112
#define IDD_DIALOG_BEHAVIOR2                    113
#define IDD_DIALOG_DISPLAY1                     120
#define IDD_DIALOG_DISPLAY2                     121
#define IDD_DIALOG_DISPLAYATTR1                 122
#define IDD_DIALOG_DISPLAYATTR2                 123
#define IDD_DIALOG_SELKEY                       131
#define IDD_DIALOG_PRSRVKEY                     132
#define IDD_DIALOG_KEYMAP1                      133
#define IDD_DIALOG_KEYMAP2                      134
#define IDD_DIALOG_CONVPOINT                    141
#define IDD_DIALOG_KANATBL                      142
#define IDD_DIALOG_JLATTBL                      143

#define IDC_LIST_SKK_DIC                        1001
#define IDC_BUTTON_SKK_DIC_ADD_FILE             1002
#define IDC_BUTTON_SKK_DIC_ADD_URL              1003
#define IDC_BUTTON_SKK_DIC_DEL                  1004
#define IDC_BUTTON_SKK_DIC_UP                   1005
#define IDC_BUTTON_SKK_DIC_DOWN                 1006
#define IDC_BUTTON_SKK_DIC_MAKE                 1007
#define IDD_DIALOG_SKK_DIC_MAKE                 1021
#define IDC_PROGRESS_DIC_MAKE                   1022
#define IDC_BUTTON_ABORT_DIC_MAKE               1023
#define IDC_CHECKBOX_SKKSRV                     1051
#define IDC_RADIO_EUC                           1052
#define IDC_RADIO_UTF8                          1053
#define IDC_EDIT_SKKSRV_HOST                    1054
#define IDC_EDIT_SKKSRV_PORT                    1055
#define IDC_EDIT_SKKSRV_TIMEOUT                 1056

#define IDC_EDIT_SKK_DIC_URL					1101

#define IDC_CHECKBOX_DEFAULTMODE                1201
#define IDC_RADIO_DEFMODEHIRA                   1202
#define IDC_RADIO_DEFMODEASCII                  1203
#define IDC_CHECKBOX_BEGINCVOKURI               1204
#define IDC_CHECKBOX_PRECEDEOKURI               1205
#define IDC_CHECKBOX_SHIFTNNOKURI               1206
#define IDC_CHECKBOX_SRCHALLOKURI               1207
#define IDC_CHECKBOX_DELCVPOSCNCL               1208
#define IDC_CHECKBOX_DELOKURICNCL               1209
#define IDC_CHECKBOX_BACKINCENTER               1210
#define IDC_CHECKBOX_ADDCANDKTKN                1211

#define IDC_COMBO_COMPMULTINUM                  1301
#define IDC_CHECKBOX_STACOMPMULTI               1302
#define IDC_CHECKBOX_DYNAMINCOMP                1303
#define IDC_CHECKBOX_DYNCOMPMULTI               1304
#define IDC_CHECKBOX_COMPUSERDIC                1305
#define IDC_CHECKBOX_COMPINCBACK                1306

#define IDC_EDIT_FONTNAME                       2001
#define IDC_EDIT_FONTPOINT                      2002
#define IDC_BUTTON_CHOOSEFONT                   2003
#define IDC_EDIT_MAXWIDTH                       2004
#define IDC_COL_BG                              2011
#define IDC_COL_FR                              2012
#define IDC_COL_SE                              2013
#define IDC_COL_CO                              2014
#define IDC_COL_CA                              2015
#define IDC_COL_SC                              2016
#define IDC_COL_AN                              2017
#define IDC_COL_NO                              2018
#define IDC_RADIO_API_GDI                       2021
#define IDC_RADIO_API_D2D                       2022
#define IDC_CHECKBOX_COLOR_FONT                 2023
#define IDC_COMBO_UNTILCANDLIST                 2031
#define IDC_CHECKBOX_DISPCANDNO                 2032
#define IDC_CHECKBOX_VERTICALCAND               2033
#define IDC_CHECKBOX_ANNOTATION                 2034
#define IDC_RADIO_ANNOTATALL                    2035
#define IDC_RADIO_ANNOTATLST                    2036
#define IDC_CHECKBOX_SHOWMODEMARK               2037
#define IDC_CHECKBOX_SHOWROMAN                  2038
#define IDC_RADIO_SHOWROMANASCII                2039
#define IDC_RADIO_SHOWROMANJLATIN               2040

#define IDC_CHECKBOX_SHOWMODEINL                2101
#define IDC_EDIT_SHOWMODESEC                    2102
#define IDC_COL_MODE_MC                         2103
#define IDC_COL_MODE_MF                         2104
#define IDC_COL_MODE_HR                         2105
#define IDC_COL_MODE_KT                         2106
#define IDC_COL_MODE_KA                         2107
#define IDC_COL_MODE_JL                         2108
#define IDC_COL_MODE_AC                         2109
#define IDC_COL_MODE_DR                         2110

#define IDC_CHECKBOX_SERIES_MARK                2201
#define IDC_CHECKBOX_SERIES_TEXT                2202
#define IDC_CHECKBOX_SERIES_OKURI               2203
#define IDC_CHECKBOX_SERIES_ANNOT               2204
#define IDC_RADIO_FG_STD_MARK                   2206
#define IDC_RADIO_FG_STD_TEXT                   2207
#define IDC_RADIO_FG_STD_OKURI                  2208
#define IDC_RADIO_FG_STD_ANNOT                  2209
#define IDC_RADIO_FG_SEL_MARK                   2211
#define IDC_RADIO_FG_SEL_TEXT                   2212
#define IDC_RADIO_FG_SEL_OKURI                  2213
#define IDC_RADIO_FG_SEL_ANNOT                  2214
#define IDC_COL_FG_MARK                         2216
#define IDC_COL_FG_TEXT                         2217
#define IDC_COL_FG_OKURI                        2218
#define IDC_COL_FG_ANNOT                        2219
#define IDC_RADIO_BG_STD_MARK                   2221
#define IDC_RADIO_BG_STD_TEXT                   2222
#define IDC_RADIO_BG_STD_OKURI                  2223
#define IDC_RADIO_BG_STD_ANNOT                  2224
#define IDC_RADIO_BG_SEL_MARK                   2226
#define IDC_RADIO_BG_SEL_TEXT                   2227
#define IDC_RADIO_BG_SEL_OKURI                  2228
#define IDC_RADIO_BG_SEL_ANNOT                  2229
#define IDC_COL_BG_MARK                         2231
#define IDC_COL_BG_TEXT                         2232
#define IDC_COL_BG_OKURI                        2233
#define IDC_COL_BG_ANNOT                        2234
#define IDC_COMBO_UL_ATTR_MARK                  2236
#define IDC_COMBO_UL_ATTR_TEXT                  2237
#define IDC_COMBO_UL_ATTR_OKURI                 2238
#define IDC_COMBO_UL_ATTR_ANNOT                 2239
#define IDC_CHECKBOX_UL_BOLD_MARK               2241
#define IDC_CHECKBOX_UL_BOLD_TEXT               2242
#define IDC_CHECKBOX_UL_BOLD_OKURI              2243
#define IDC_CHECKBOX_UL_BOLD_ANNOT              2244
#define IDC_RADIO_UL_STD_MARK                   2246
#define IDC_RADIO_UL_STD_TEXT                   2247
#define IDC_RADIO_UL_STD_OKURI                  2248
#define IDC_RADIO_UL_STD_ANNOT                  2249
#define IDC_RADIO_UL_SEL_MARK                   2251
#define IDC_RADIO_UL_SEL_TEXT                   2252
#define IDC_RADIO_UL_SEL_OKURI                  2253
#define IDC_RADIO_UL_SEL_ANNOT                  2254
#define IDC_COL_UL_MARK                         2256
#define IDC_COL_UL_TEXT                         2257
#define IDC_COL_UL_OKURI                        2258
#define IDC_COL_UL_ANNOT                        2259
#define IDC_COMBO_ATTR_MARK                     2261
#define IDC_COMBO_ATTR_TEXT                     2262
#define IDC_COMBO_ATTR_OKURI                    2263
#define IDC_COMBO_ATTR_ANNOT                    2264

#define IDC_LIST_SELKEY                         3101
#define IDC_EDIT_SELKEY_DISP                    3102
#define IDC_EDIT_SELKEY_SPARE                   3103
#define IDC_BUTTON_SELKEY_W                     3104

#define IDC_LIST_PRSRVKEY_ON                    3201
#define IDC_LIST_PRSRVKEY_OFF                   3202
#define IDC_EDIT_PRSRVKEY_VKEY                  3203
#define IDC_CHECKBOX_PRSRVKEY_MKEY_ALT          3204
#define IDC_CHECKBOX_PRSRVKEY_MKEY_CTRL         3205
#define IDC_CHECKBOX_PRSRVKEY_MKEY_SHIFT        3206
#define IDC_RADIO_PRSRVKEY_ON                   3207
#define IDC_RADIO_PRSRVKEY_OFF                  3208
#define IDC_BUTTON_PRSRVKEY_UP                  3209
#define IDC_BUTTON_PRSRVKEY_DOWN                3210
#define IDC_BUTTON_PRSRVKEY_W                   3211
#define IDC_BUTTON_PRSRVKEY_D                   3212
#define IDC_EDIT_DISPVKEY                       3221

#define IDC_EDIT_KANA                           3301
#define IDC_EDIT_CONV_CHAR                      3302
#define IDC_EDIT_JLATIN                         3303
#define IDC_EDIT_ASCII                          3304
#define IDC_EDIT_JMODE                          3305
#define IDC_EDIT_ABBREV                         3306
#define IDC_EDIT_AFFIX                          3307
#define IDC_EDIT_NEXT_CAND                      3308
#define IDC_EDIT_PREV_CAND                      3309
#define IDC_EDIT_PURGE_DIC                      3310
#define IDC_EDIT_NEXT_COMP                      3311
#define IDC_EDIT_PREV_COMP                      3312
#define IDC_EDIT_HINT                           3313
#define IDC_EDIT_CONV_POINT                     3321
#define IDC_EDIT_DIRECT                         3322
#define IDC_EDIT_ENTER                          3323
#define IDC_EDIT_CANCEL                         3324
#define IDC_EDIT_BACK                           3325
#define IDC_EDIT_DELETE                         3326
#define IDC_EDIT_VOID                           3327
#define IDC_EDIT_LEFT                           3328
#define IDC_EDIT_UP                             3329
#define IDC_EDIT_RIGHT                          3330
#define IDC_EDIT_DOWN                           3331
#define IDC_EDIT_PASTE                          3332

#define IDC_LIST_CONVPOINT                      4101
#define IDC_EDIT_CONVPOINT_ST                   4102
#define IDC_EDIT_CONVPOINT_AL                   4103
#define IDC_EDIT_CONVPOINT_OK                   4104
#define IDC_BUTTON_CONVPOINT_UP                 4105
#define IDC_BUTTON_CONVPOINT_DOWN               4106
#define IDC_BUTTON_CONVPOINT_W                  4107
#define IDC_BUTTON_CONVPOINT_D                  4108

#define IDC_LIST_KANATBL                        4201
#define IDC_EDIT_KANATBL_R                      4202
#define IDC_EDIT_KANATBL_H                      4203
#define IDC_EDIT_KANATBL_K                      4204
#define IDC_EDIT_KANATBL_KA                     4205
#define IDC_CHECKBOX_KANATBL_SOKU               4206
#define IDC_CHECKBOX_KANATBL_WAIT               4207
#define IDC_BUTTON_KANATBL_UP                   4208
#define IDC_BUTTON_KANATBL_DOWN                 4209
#define IDC_BUTTON_KANATBL_W                    4210
#define IDC_BUTTON_KANATBL_D                    4211
#define IDC_BUTTON_LOADKANA                     4212
#define IDC_BUTTON_SAVEKANA                     4213

#define IDC_LIST_JLATTBL                        4301
#define IDC_EDIT_JLATTBL_A                      4302
#define IDC_EDIT_JLATTBL_J                      4303
#define IDC_BUTTON_JLATTBL_UP                   4304
#define IDC_BUTTON_JLATTBL_DOWN                 4305
#define IDC_BUTTON_JLATTBL_W                    4306
#define IDC_BUTTON_JLATTBL_D                    4307

#endif //RESOURCE_H
